# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sMCB_G-ZEUROibL8cOiqvk8YyI6mQfNQ
"""

!pip install spacy
!python -m spacy download pl_core_news_sm

import spacy
import re # Biblioteka do wzorców (RegEx)
from IPython.display import display, HTML
import ipywidgets as widgets

nlp = spacy.load("pl_core_news_sm")

def anonimizuj_wszystko(tekst):
    # 1. Najpierw usuwamy PESEL (11 cyfr)
    tekst = re.sub(r'\b\d{11}\b', '[PESEL]', tekst)

    # 2. Usuwamy numery dowodów osobistych (3 litery + 6 cyfr)
    tekst = re.sub(r'\b[A-Z]{3}\s?\d{6}\b', '[DOWÓD OSOBISTY]', tekst)

    # 3. Usuwamy adresy e-mail
    tekst = re.sub(r'\b[\w\.-]+@[\w\.-]+\.\w{2,}\b', '[E-MAIL]', tekst)

    # 4. Na koniec spacy zajmuje się imionami, nazwiskami i miastami
    doc = nlp(tekst)
    wynik = tekst
    for ent in reversed(doc.ents):
        if ent.label_ in ["persName", "placeName", "orgName"]:
            wynik = wynik[:ent.start_char] + f"<strong>[{ent.label_}]</strong>" + wynik[ent.end_char:]

    return wynik

# Interfejs
print("--- URZĘDOWY POMOCNIK v2.0 (z obsługą PESEL) ---")
pole_tekstowe = widgets.Textarea(
    placeholder='Wklej tekst zawierający imiona i numery PESEL...',
    description='Tekst:',
    layout={'height': '200px', 'width': '90%'}
)
przycisk = widgets.Button(description="Anonimizuj Wszystko", button_style='danger')
output = widgets.Output()

def on_button_clicked(b):
    with output:
        output.clear_output()
        wynik = anonimizuj_wszystko(pole_tekstowe.value)
        display(HTML(f"<b>Wynik:</b><br><div style='border:1px solid #ccc; padding:10px;'>{wynik}</div>"))

przycisk.on_click(on_button_clicked)
display(pole_tekstowe, przycisk, output)